### ISSUE TITLE
Error : undefined method 'gsub'

### ISSUE THREAD

**Issue by Fourchaux** [trou/arteget#1]
Avec ruby 2.0.0p648 (2015-12-16 revision 53162) & [x86_64-linux]

La commande :
```
$ ./arteget.rb list
```
affiche :
```
Getting index
./arteget.rb:323:in `get_progs_json': undefined method `gsub' for nil:NilClass (NoMethodError)
      from ./arteget.rb:336:in `list_progs'
      from ./arteget.rb:396:in `<main>'
```
Grigri connu ?

**Comment by trou** [comment]
oui ça ne marche plus, c'est "corrigé" dans la version git (en ce sens que la fonctionnalité n'existe plus).
